# basics

HISTFILE=~/.histfile
EDITOR=nvim
VISUAL=nvim

# options

unsetopt beep
bindkey -e
setopt HIST_IGNORE_DUPS

# aliases
alias vim=nvim
alias dock="docker-compose"

# Set PATH, MANPATH, etc., for Homebrew.
eval "$(/opt/homebrew/bin/brew shellenv)"

# syntax highlighting
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# prompt
fpath+=("$(brew --prefix)/share/zsh/site-functions")

autoload -Uz compinit promptinit; compinit; promptinit;
prompt typewritten

export TYPEWRITTEN_PROMPT_LAYOUT="pure"
export TYPEWRITTEN_CURSOR="block"

# direnv
eval "$(direnv hook zsh)"

# pipx
export PATH="$HOME/.local/bin:$PATH"

# python
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"

# ruby
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# npm
export PATH="$HOME/.npm-packages/bin:$PATH"

# Go
export GOPATH="$HOME/Work/go"
export PATH="$GOPATH/bin:$PATH"

# Rust
source "$HOME/.cargo/env"

# pkgconfig
export PKG_CONFIG_PATH="/opt/homebrew/opt/mysql-client/lib/pkgconfig"

# PostgreSQL
export PATH="/opt/homebrew/opt/postgresql@16/bin:$PATH"

# Windsurf
export PATH="/Users/siddhant/.codeium/windsurf/bin:$PATH"
